
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

bg_color = "#1D2951"
border_color = "#8B8B8B"

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/maceccar/Desktop/Flagle/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("300x700")
window.configure(bg = bg_color)


canvas = Canvas(
    window,
    bg = "#1D2951",
    height = 700,
    width = 300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)

#Footer
canvas.create_rectangle(
    7.996467590332031,
    661.0,
    291.00354766845703,
    696.0,
    fill=bg_color,
    outline="")

# Guess
canvas.create_rectangle(
    26.0,
    599.0,
    273.0,
    643.0,
    fill=bg_color,
    outline=border_color)

#Sixth try
canvas.create_rectangle(
    26.0,
    521.0,
    273.0,
    565.0,
    fill=bg_color,
    outline=border_color)

#Fifth try
canvas.create_rectangle(
    26.0,
    460.0,
    273.0,
    504.0,
    fill=bg_color,
    outline=border_color)

#Fourth try
canvas.create_rectangle(
    26.0,
    399.0,
    273.0,
    443.0,
    fill=bg_color,
    outline=border_color)

#Third try
canvas.create_rectangle(
    26.0,
    338.0,
    273.0,
    382.0,
    fill=bg_color,
    outline=border_color)

#Second try
canvas.create_rectangle(
    26.0,
    277.0,
    273.0,
    321.0,
    fill=bg_color,
    outline=border_color)

#First try
canvas.create_rectangle(
    26.0,
    216.0,
    273.0,
    260.0,
    fill=bg_color,
    outline=border_color)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    149.0,
    109.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
