
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("300x700")
window.configure(bg = "#1D2951")


canvas = Canvas(
    window,
    bg = "#1D2951",
    height = 700,
    width = 300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    6.996467590332031,
    660.0,
    291.00354766845703,
    661.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    90.0,
    666.0,
    anchor="nw",
    text="FLAGLE ",
    fill="#FFFFFF",
    font=("Inter Bold", 30 * -1)
)

canvas.create_rectangle(
    26.0,
    599.0,
    273.0,
    643.0,
    fill="#1D2951",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    121.5,
    621.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=32.0,
    y=606.0,
    width=179.0,
    height=28.0
)

canvas.create_rectangle(
    26.0,
    521.0,
    273.0,
    565.0,
    fill="#1D2951",
    outline="")

canvas.create_rectangle(
    215.0,
    524.0,
    216.0,
    560.0,
    fill="#8A8A8A",
    outline="")

canvas.create_text(
    32.0,
    534.0,
    anchor="nw",
    text="Sixth try",
    fill="#8A8A8A",
    font=("Inter Bold", 15 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=235.0,
    y=606.0,
    width=29.0,
    height=29.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    245.0,
    542.0,
    image=image_image_1
)

canvas.create_rectangle(
    26.0,
    460.0,
    273.0,
    504.0,
    fill="#1D2951",
    outline="")

canvas.create_rectangle(
    215.0,
    463.0,
    216.0,
    499.0,
    fill="#8A8A8A",
    outline="")

canvas.create_text(
    32.0,
    473.0,
    anchor="nw",
    text="Fifth try",
    fill="#8A8A8A",
    font=("Inter Bold", 15 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    245.0,
    481.0,
    image=image_image_2
)

canvas.create_rectangle(
    26.0,
    399.0,
    273.0,
    443.0,
    fill="#1D2951",
    outline="")

canvas.create_rectangle(
    215.0,
    402.0,
    216.0,
    438.0,
    fill="#8A8A8A",
    outline="")

canvas.create_text(
    32.0,
    412.0,
    anchor="nw",
    text="Fourth try",
    fill="#8A8A8A",
    font=("Inter Bold", 15 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    245.0,
    420.0,
    image=image_image_3
)

canvas.create_rectangle(
    26.0,
    338.0,
    273.0,
    382.0,
    fill="#1D2951",
    outline="")

canvas.create_rectangle(
    215.0,
    341.0,
    216.0,
    377.0,
    fill="#8A8A8A",
    outline="")

canvas.create_text(
    32.0,
    351.0,
    anchor="nw",
    text="Third try",
    fill="#8A8A8A",
    font=("Inter Bold", 15 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    245.0,
    359.0,
    image=image_image_4
)

canvas.create_rectangle(
    26.0,
    277.0,
    273.0,
    321.0,
    fill="#1D2951",
    outline="")

canvas.create_rectangle(
    215.0,
    280.0,
    216.0,
    316.0,
    fill="#8A8A8A",
    outline="")

canvas.create_text(
    32.0,
    290.0,
    anchor="nw",
    text="Second try",
    fill="#8A8A8A",
    font=("Inter Bold", 15 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    245.0,
    298.0,
    image=image_image_5
)

canvas.create_rectangle(
    26.0,
    216.0,
    273.0,
    260.0,
    fill="#1D2951",
    outline="")

canvas.create_rectangle(
    215.0,
    219.0,
    216.0,
    255.0,
    fill="#8A8A8A",
    outline="")

canvas.create_text(
    31.0,
    229.0,
    anchor="nw",
    text="First try",
    fill="#8A8A8A",
    font=("Inter Bold", 15 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    245.0,
    237.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    149.0,
    109.0,
    image=image_image_7
)
window.resizable(False, False)
window.mainloop()
